// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2eatZdS72F9EBgQ90y1trtm6a3fhp7tU',
    appId: '1:526781682875:web:563b6c9630f20abb83059e',
    messagingSenderId: '526781682875',
    projectId: 'bookpicker-629d0',
    authDomain: 'bookpicker-629d0.firebaseapp.com',
    storageBucket: 'bookpicker-629d0.appspot.com',
    measurementId: 'G-WGXSJY57GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC81xoXI6N0YprwkYnWrbJx2FLudMCQ0Co',
    appId: '1:526781682875:android:c581d6b412bfeecc83059e',
    messagingSenderId: '526781682875',
    projectId: 'bookpicker-629d0',
    storageBucket: 'bookpicker-629d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG0F9Vx2qqQLv6l25RXmC2WosK7Hz4GfY',
    appId: '1:526781682875:ios:4272b195a2141b4283059e',
    messagingSenderId: '526781682875',
    projectId: 'bookpicker-629d0',
    storageBucket: 'bookpicker-629d0.appspot.com',
    iosBundleId: 'com.example.bookPicker',
  );
}
