name: book_picker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.2.1
  hooks_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  geolocator: ^10.1.0
  flutter_riverpod: ^2.4.5
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  dio: ^5.4.0
  riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
