name: book_picker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.5
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  dio: ^5.4.0
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.11
  go_router: ^13.2.0
  persistent_bottom_nav_bar: ^5.0.2
  envied: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
