name: book_picker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.4.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.5
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  dio: ^5.4.0
  riverpod_annotation: ^2.3.4
  riverpod_generator: ^2.3.11
  go_router: ^13.2.0
  persistent_bottom_nav_bar: ^5.0.2
  envied: ^0.5.3
  glassmorphism: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.4
  font_awesome_flutter: ^10.7.0
  lottie: ^3.0.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^5.0.0
  intl: ^0.19.0
  badges: ^3.1.2
  loading_animation_widget: ^1.2.0+4
  package_info_plus: ^5.0.1
  firebase_remote_config: ^4.3.14
  google_mobile_ads: ^4.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: KiwiMaru
      fonts:
        - asset: assets/fonts/KiwiMaru-Light.ttf
        - asset: assets/fonts/KiwiMaru-Medium.ttf
        - asset: assets/fonts/KiwiMaru-Regular.ttf
